name: Auto Train Chatbot

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'models/**'
      - 'training/**'
      - 'utils/**'
  schedule:
    # 매주 월요일 오전 9시에 자동 학습
    - cron: '0 9 * * 1'
  workflow_dispatch: # 수동 실행 가능

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Collect data
      run: |
        python utils/data_collector.py
        
    - name: Check data quality
      run: |
        python utils/data_quality_checker.py
        
    - name: Train model
      run: |
        python training/train_pytorch.py
        
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: |
          models/checkpoints/
          data/quality_conversations.json
          utils/tokenizer.pkl
        
    - name: Commit and push updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto update: Model retrained with new data"
        git push 